name: luminagrade
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  file_picker: ^13.1.0
  path_provider: ^2.1.5
  video_player: ^2.10.0
  share_plus: ^13.3.0
  cross_file: ^0.3.5
  ffmpeg_kit_flutter_new_full: ^2.5.2

flutter:
  uses-material-design: true
